### PR TITLE
Fix type error

### PR DESCRIPTION
**Pull request by ngmy**
I ran the `composer phpstan` command on the `main` branch and got an error, so I fixed it using the [global type alias](https://phpstan.org/writing-php-code/phpdoc-types#global-type-aliases).

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, I don't think this workaround is the right way to go as this would crash if php-parser 4.18 is installed.

For now, ignore the error in `phpstan.neon` or lock packages to php-parser 4.18.

**Comment by ngmy** [comment]
Hi, I have locked the packages to php-parser 4.18.

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Pull request merged**
