### PR TITLE
Declare PHP 8.1/8.2 compat

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
That's wrong. The release have to be idempotent, otherwise composer might install 2 different code versions.

The main release is for PHP 8.1+

**Comment by staabm** [comment]
the current release is not installable:

https://github.com/staabm/phpstan-baseline-analysis/pull/86

https://github.com/staabm/phpstan-baseline-analysis/actions/runs/3765019049/jobs/6400056653

**Comment by TomasVotruba** [comment]
It is, this is PHP 8.0 fresh install: 

Screenshot from 2022-12-23 12-10-06

**Comment by staabm** [comment]
oh sorry, .. I mixed it up with the other package
```
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tomasvotruba/type-coverage 0.0.1 requires php ^8.1 -> your php version (8.0.26) does not satisfy that requirement.
    - tomasvotruba/type-coverage 0.0.1.72 requires php ^7.2|8.0 -> your php version (8.0.26) does not satisfy that requirement.
    - Root composer.json requires tomasvotruba/type-coverage ^0.0.1 -> satisfiable by tomasvotruba/type-coverage[0.0.1, 0.0.1.72].


  Problem 1
    - tomasvotruba/type-coverage 0.0.1 requires php ^8.1 -> your php version (8.0.26) does not satisfy that requirement.
    - tomasvotruba/type-coverage 0.0.1.72 requires php ^7.2|8.0 -> your php version (8.0.26) does not satisfy that requirement.
    - Root composer.json requires tomasvotruba/type-coverage ^0.0.1 -> satisfiable by tomasvotruba/type-coverage[0.0.1, 0.0.1.72].
```

**Comment by TomasVotruba** [comment]
~~Maybe there is something special about 0.0.1 version. I've added 0.0.2 and it just works :D~~

...ah, I was on PHP 8.1. The 8.0 is still stuck, in progress

**Comment by staabm** [comment]
> The release have to be idempotent, otherwise composer might install 2 different code versions.

oohh I now realize how this thing works. you publish each release twice. once for 7.2-8.0 and one for 8.1+

**Comment by TomasVotruba** [comment]
Exactly :)

I wrote about it here, it might help: https://tomasvotruba.com/blog/how-to-develop-sole-package-in-php81-and-downgrade-to-php72/

I've added the CI job to test install on relevant PHP versions to be sure it works ↓
https://github.com/TomasVotruba/type-coverage/blob/main/.github/workflows/various_php_install.yaml

**Comment by staabm** [comment]
works now, thank you

**Comment by TomasVotruba** [comment]
Glad to hear that :+1:  
Thanks for feedback and kicking me to add the install check to CI :laughing:

**Comment by staabm** [comment]
we are one big open source family, right? :)

<3

**Comment by TomasVotruba** [comment]
Exactly :love_you_gesture:  it feels exciting to be in company of smart and always-growing people like you :pray: 

It makes me feel to naturally get the best of me :)

**Pull request closed without merging**
